### ISSUE TITLE
Ajouter les rangs limites pour la spécialité

### ISSUE THREAD

**Issue by ghost** [AdGui/CarteECN#1]
Sur la version présente sur http://shiny.adgui.eu/, je ne vois pas le rang limite pour une spécialité donnée (celle selectionnée dans options globales) pour chaque subdivision. 

Excellent travail! C'est classe. Il faudrait le mettre en avant, peut être un lien sur le site du CliSP?

**Comment by AdGui** [comment]
C'est que je n'ai pas répercuté une partie du code de l'appli que j'avais fait l'été dernier (tout ce qui concerne les spés). En theorie on peut avoir une idée des rangs limites approximatifs en selectionnant le pourcentage de poste pourvus et en restreignant le nombre de candidat... Mais c'est assez lourd !
Ca peut facilement être rajouté, merci pour l'idée !

Je pense qu'il y'a encore 2-3 trucs à changer au niveau de l'apparence pour que ça soit vraiment diffusable (c'est un peu le bazar dans les options de la carte)... Et je fusionnerai bien avec la première appli. Mais à terme je l'enverrai sans doute au CLISP.

**Comment by AdGui** [comment]
Les données sur les rangs (médiane, moyenne...) sont maintenant modulables selon la spé. J'ai rajouté le rang limite (soit égal au max, soit inférieur au max si CESP, soit égal au rang max toute spé confondues + 1 si tous les postes ne sont pas remplies)..
