### ISSUE TITLE
Ergonomie : Bloquer niveau de Zoom

### ISSUE THREAD

**Issue by ghost** [AdGui/CarteECN#2]
Sur la version sur http://shiny.adgui.eu/, l'utilisateur peut changer le zoom sur la carte, ce qui a peu d'intérêt étant donné que l'on ne cherche que de l'information au niveau régional (en fait subdivisions). Donc peut être bloquer le niveau de zoom pour éviter fausse manipulation. En effet, en naviguant sur la page avec la molette, lorsque l'on arrive sur la carte on a tendance à changer le niveau de zoom.

**Comment by AdGui** [comment]
J'aime bien l'idée de pouvoir zoomer (essentiellement parce que je suis content d'avoir réussi à en donner la possibilité !), même si ça n'a pas grand intérêt dans l'appli (à part éventuellement pour des petits écrans ou écran en 4/3)... Mais je peux restreindre à 3 niveau de zoom ça devrait suffire pour ne pas trop gêner lors des mouvement de molette.

**Comment by AdGui** [comment]
Modification faite !

**Comment by ghost** [comment]
Belle réactivité! Merci
