### ISSUE TITLE
JavaScript Error console

### ISSUE THREAD

**Issue by ghost** [AdGui/CarteECN#3]
Lorsque je tente d'ouvrir l'application sur [http://shiny.adgui.eu/](http://shiny.adgui.eu/), j'obtient le message d'alerte suivant :

> The application unexpectedly exited.
> Diagnostic information has been dumped to the JavaScript error console

Testé sur Firefox 37.0.1 et Safari 8.0.5 sous MacOS X 10.10.3

**Comment by AdGui** [comment]
Tu es tombé juste au moment où je tentais de voir d'où venais l'erreur (j'avais bien uploadé server.R mais pas ui.R...). Maintenant ça devrait fonctionner !
